/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PointsOfIntrestIndexImport } from './routes/points-of-intrest/index'

// Create/Update Routes

const PointsOfIntrestIndexRoute = PointsOfIntrestIndexImport.update({
  id: '/points-of-intrest/',
  path: '/points-of-intrest/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/points-of-intrest/': {
      id: '/points-of-intrest/'
      path: '/points-of-intrest'
      fullPath: '/points-of-intrest'
      preLoaderRoute: typeof PointsOfIntrestIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/points-of-intrest': typeof PointsOfIntrestIndexRoute
}

export interface FileRoutesByTo {
  '/points-of-intrest': typeof PointsOfIntrestIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/points-of-intrest/': typeof PointsOfIntrestIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/points-of-intrest'
  fileRoutesByTo: FileRoutesByTo
  to: '/points-of-intrest'
  id: '__root__' | '/points-of-intrest/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PointsOfIntrestIndexRoute: typeof PointsOfIntrestIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  PointsOfIntrestIndexRoute: PointsOfIntrestIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/points-of-intrest/"
      ]
    },
    "/points-of-intrest/": {
      "filePath": "points-of-intrest/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
